import { Noto_Sans_JP } from "next/font/google";
import "./globals.css";
import Myheader from "./components/header";
import Footer from "./components/footer";

const NotoSans = Noto_Sans_JP({
  subsets: ["latin"],
  display: "swap",
  preload: true,
});

export const metadata = {
  title: "CS-13 Virtual Lab Tour ",
  description: "Generated by create next app",
};

type RootLayoutProps = {
  children: React.ReactNode;
};

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="jp" className="bg-black">
      <body className={NotoSans.className}>
        <Myheader />
        <main className="pt-20">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
