import { Noto_Sans_JP } from "next/font/google";
import "./globals.css";
import Myheader from "./components/header";

const NotoSans = Noto_Sans_JP({
  subsets: ["latin"],
  display: "swap",
  preload: true,
});

export const metadata = {
  title: "CS-13 Virtual Lab Tour ",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="jp">
      <body className={NotoSans.className}>
        <Myheader />
        <main className="pt-20">{children}</main>
      </body>
    </html>
  );
}
